name: Update Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.tgz'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Helm Installation
        uses: Azure/setup-helm@v2.0
        with:
          version: v3.9.0

      - name: Update Index
        run: |
          helm repo index .
          git add index.yaml
          git commit -m "Update chart index"
          git push